SELECT 
    t.KODE,
    t.TANGGAL,
    p.NAMA AS NAMA_PELANGGAN,
    b.NAMA AS NAMA_BARANG,
    t.JUMLAH_BARANG AS JUMLAH,
    b.HARGA_SATUAN,
    (t.JUMLAH_BARANG * b.HARGA_SATUAN) AS TOTAL
FROM 
    transaksi t
INNER JOIN pelanggan p ON t.KODE_PELANGGAN = p.KODE_PELANGGAN
INNER JOIN barang b ON t.KODE_BARANG = b.KODE_BARANG;